### PR TITLE
setup for GitHub Enterprise

### LINKED ISSUE #40: Adapt quarto-actions/setup for use in GitHub Enterprise?
I'm starting to experiment with quarto (and r-lib) actions in GitHub Enterprise (GHE). Things are *mostly* working, with a few snags here-and-there.

I have encountered a snag in the setup action:

https://github.com/quarto-dev/quarto-actions/blob/f8db812b12a3c93a53113d4e01910d672e17ab09/setup/action.yml#L42-L43

As I understand, `gh` assumes you are working with GitHub and that you have a valid GitHub token.

I can get around the first problem by adding the host:

```
gh release download --repo github.com/quarto-dev/quarto-cli --pattern ${{ format('*{0}', env.BUNDLE_EXT) }}
```

But the second problem remains: on GHE, `GITHUB_TOKEN` works on GHE - not GitHub proper.

I can work around this problem by specifying a version in my action workflow, e.g.:

```yaml
      - name: Set up Quarto
        uses: <local-fork>/quarto-actions/setup@v2
        with:
          version: 1.0.38
```

Could there be a way to make the "stable release" method robust to use on GitHub Enterprise?

To be clear, this is **not** an urgent issue. The wheels of progress can turn slowly at big companies; we are a long way from rolling anything out internally.

Thanks!

### PR DESCRIPTION
**Pull request by ijlyttle**
fix #40 

I took a first swing at documentation; I will be happy to revise as you wish.

Thanks!

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you! Interesting, this turns out to be simpler than I thought.

@cderv this looks good to me, what do you think?

**Comment by ijlyttle** [comment]
Hi @cderv - I have tested it on our instance, and it works for me™️.

Also, FWIW, because you are using the [newer syntax for setting outputs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), the runner version has to be at least 2.298.2.

I have a larger question about support for GitHub Enterprise, but the challenge is procedural, rather than technical. I don't think this thread is the right venue, so I'll use another venue.

**Comment by cderv** [comment]
> because you are using the [newer syntax for setting outputs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), the runner version has to be at least 2.298.2.

We did the change because of this post and Github warning about deprecation. :) 
So you mean our action won't work on GHE server that would run previous syntax, is that so ? 

For now it would mean that you need to use a specific tag (probably `@2.0.3`) so that you don't get the change. We could also maintain a specific branch or specific tag if that helps. 

We'll see what comes from the discussion in the other venue. 

Thanks for the PR

**Comment by ijlyttle** [comment]
@cderv - no worries about the change, we upgraded the runner-version ourselves recently. It was just another thing for me to learn about 😅

I agree, using a specific branch or tag could be useful here.

**Comment by cderv** [comment]
> I agree, using a specific branch or tag could be useful here.

We'll see if we find other specificity then.

**Pull request merged**
